import mpmath
import common

fl0 = lambda x: mpmath.legendre(0,x)
fl1 = lambda x: mpmath.legendre(1,x)
fl2 = lambda x: mpmath.legendre(2,x)
fl3 = lambda x: mpmath.legendre(3,x)
fl4 = lambda x: mpmath.legendre(4,x)
fl5 = lambda x: mpmath.legendre(5,x)
fh0 = lambda x: mpmath.hermite(0,x)
fh1 = lambda x: mpmath.hermite(1,x)
fh2 = lambda x: mpmath.hermite(2,x)
fh3 = lambda x: mpmath.hermite(3,x)
fh4 = lambda x: mpmath.hermite(4,x)
fh5 = lambda x: mpmath.hermite(5,x)
fc0 = lambda x: mpmath.chebyt(0,x)
fc1 = lambda x: mpmath.chebyt(1,x)
fc2 = lambda x: mpmath.chebyt(2,x)
fc3 = lambda x: mpmath.chebyt(3,x)
fc4 = lambda x: mpmath.chebyt(4,x)
fc5 = lambda x: mpmath.chebyt(5,x)
mpmath.plot([fl0,fl1,fl2,fl3,fl4,fl5],[-1,1])
mpmath.plot([fh0,fh1,fh2,fh3,fh4,fh5],[-1,1])
mpmath.plot([fc0,fc1,fc2,fc3,fc4,fc5],[-1,1])