from .nlconvolution_powerseries import nonlinearconvolution_powerseries,nonlinearconvolution_powerseries_debug,\
    nonlinearconvolution_powerseries_novak

from .nlconvolution_chebyshev import nonlinearconvolution_chebyshev

from .nlconvolution_cosine import nonlinearconvolution_chebyshev_cosine

from .nl_convolution import NLConvolution
